# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# https://github.com/MicrosoftDocs/pipelines-javascript/blob/master/azure-pipelines.yml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: | 
    pwd

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: 
    npm test
  displayName: 'Run test'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test-results.xml'
    testRunTitle: 'Test results for JavaScript'
