jobs:
- job: Foo

  steps:      
  - script: echo Hello!
    
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
      
  - script: |
      cd '$(Build.SourcesDirectory)/NodeApp'
      npm install
    displayName: 'npm install'

  - script: |
      cd '$(Build.SourcesDirectory)/NodeApp'
      npm test
    displayName: 'Run test'

- job: Bar
  dependsOn: Foo
  condition: failed() # this job will only run if Foo fails
  
  steps:
  - script: echo Failed!
