jobs:
- job: Foo

  steps:
  - script: echo Hello!
    
  - task: NodeTool@0
    inputs:
    versionSpec: '8.x'
    displayName: 'Install Node.js'

- job: Bar
  dependsOn: Foo
  condition: failed() # this job will only run if Foo fails
