# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# https://github.com/MicrosoftDocs/pipelines-javascript/blob/master/azure-pipelines.yml
#by Daniel h

pool:
  vmImage: 'Ubuntu 16.04'

variables:
    nodeDir: '$(Build.SourcesDirectory)/NodeApp'
    artifactDir: '$(Build.ArtifactStagingDirectory)'
    foo: 'default'

steps:
- script: | 
    echo '$(artifactDir)'
    docker images

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    cd '$(nodeDir)'
    npm install
  displayName: 'npm install'

- powershell: |
    npm test
    if ($LASTEXITCODE -eq 1) {
      Write-Output "The npm test has failed"
      "Failed" | Set-Content  "test.failed"
    }
  displayName: 'Run test'
  continueOnError: true
  errorActionPreference: silentlyContinue
  workingDirectory: '$(nodeDir)'
  
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(nodeDir)/test-results.xml'
    testRunTitle: 'Test results for JavaScript'
    
- powershell: |
    cd '$(nodeDir)'
    if (Test-Path test.failed) {
      Write-Error "Test failed"
    }
  displayName: 'Test Status'

- script: |
    docker build -t 'hacky1610/azurenodeapp:$(Build.BuildId)' .
    docker images
    docker login -u hacky1610 -p '$(hacky.docker.pwd)'
    docker push 'hacky1610/azurenodeapp:$(Build.BuildId)'
  displayName: 'Build docker'
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(nodeDir)' 
    artifactName: 'drop' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
